### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by RdecKa** [jakoberzar/advent-of-code-2017#1]
The file with solutions for Day 3 seem to be missing. Is adding it to the repository in your near future plans? Can we expect to get it?

**Comment by jakoberzar** [comment]
Indeed, I am one day late with the solution to day 3. I will add it in the upcoming days. Are you dependant on it? How soon do you need it? I will see what I can do about it.

**Comment by RdecKa** [comment]
I need it by yesterday, thanks.

**Comment by jakoberzar** [comment]
Very well, too bad then!
